version: "3"
services:
  mymongodb:
    image: mongo
    container_name: "mymongodb"
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - '7081:8081'
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_SERVER: 'mymongodb'
    restart: always
    links:
      - mymongodb